spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    url: jdbc:mysql://localhost:3306/coupon?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: coupon_local_rw
    password: e4c9410535f7
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

redisson:
  config: classpath:config/local/redisson-local.yml

logging:
  level:
    org.springframework.security: TRACE